# Generated by Django 4.2.9 on 2024-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_employee_salary_alter_payment_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='event_name',
            new_name='eventname',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=100),
        ),
    ]
