# Generated by Django 4.2.9 on 2024-03-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_rename_event_name_payment_eventname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='eventname',
            new_name='name',
        ),
    ]
