# Generated by Django 4.2.9 on 2024-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_eventname_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
