# Generated by Django 4.2.9 on 2024-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_event_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Customer_name',
        ),
    ]
